### ISSUE TITLE
Searching Tells Function

### ISSUE THREAD

**Issue by lh-import** [cakephp/irc.cakephp.org#4]
Created by **carbontwelve**, 15th Apr 2011. _(originally [Lighthouse ticket #6](http://cakephp.lighthouseapp.com/projects/43068/tickets/6))_:

---

You should be able to search tells rather than just the chat log.

**Comment by josegonzalez** [comment]
This was completed and should be live once dns for irc.cakephp.org switches to the new server. Thanks all.
