### ISSUE TITLE
Upgrade logs/tells/bot to CakePHP3

### ISSUE THREAD

**Issue by dereuromark** [cakephp/irc.cakephp.org#6]
One often asked feature was https://github.com/cakephp/cakebot/issues/4
But besides that one, it would be very good if that app would be upgraded/rewritten to/in CakePHP 3.0.

Anything else that we would want then?
Maybe we can collect all these infos beforehand and then quickly implement them.

**Comment by josegonzalez** [comment]
I've upgraded to CakePHP 3 and implemented that functionality. The bot now lives [in this cakebot repository](https://github.com/cakephp/cakebot), while this repository is for the website.
