### ISSUE TITLE
Is there any reason for the block on number of pages we are able to go back?

### ISSUE THREAD

**Issue by voycey** [cakephp/irc.cakephp.org#8]
https://github.com/cakephp/irc.cakephp.org/blob/6fd8df9196c1c4dc35ac8ce4fb4eca721af20ca9/src/Controller/LogsController.php#L64

For example in search it would be great to be able to go back through the full history.

Perhaps if ->last could be implemented that would be enough?

**Comment by ADmad** [comment]
You can make a donation to CSF to get the full db dump :trollface:.

**Comment by voycey** [comment]
No worries - figured it was something related to performance!
